const bands = [
    { name: 'Black Sabbath', land: "UK" },
    { name: 'death', land: "US" },
    { name: 'Iron Maiden', land: "UK" },
    { name: 'Rhapsody', land: "IT" },
    { name: 'The Beatles', land: "UK" },
    { name: 'The Doors', land: "US" },
    { name: 'Gentle Giant', land: "UK" },
    { name: 'Dream Theater', land: "US" },
    { name: 'Voivod', land: "CA" },
    { name: 'AC/DC', land: "AU" },
    { name: 'Kreator', land: "DE" },
    { name: 'Overkill', land: "US" },
    { name: 'Pražský Výběr', land: "CZE" },
    { name: 'Motorhed', land: "UK" } ,
    { name: 'Arch Enemy', land: "US" },
    { name: 'Judas Priest', land: "UK" },
    { name: 'Cytotoxin', land: "DE" },
    { name: 'King Crimson', land: "UK" },
    { name: 'Pink Floyd', land: "UK" },
];