export const genres = [
    {id: "1", name: "metal", parent: null},
        {id: "1.1", name: "death metal", parent: "1"},   
            {id: "1.1.1", name: "old school death", parent: "1.1"},   
            {id: "1.1.2", name: "technical death", parent: "1.1"},   
            {id: "1.1.3", name: "progressive death", parent: "1.1"},   
            {id: "1.1.3", name: "melodeath", parent: "1.1"},   
        {id: "1.2", name: "heavy metal", parent: "1"},
        {id: "1.3", name: "power metal", parent: "1"},
        {id: "1.4", name: "progressive metal", parent: "1"},
            {id: "1.4.1", name: "traditional prog metal", parent: "1.4"},
            {id: "1.4.2", name: "progressive death", parent: "1.4"},
            {id: "1.4.1", name: "progressive black", parent: "1.4"},
            {id: "1.4.2", name: "progressive thrash", parent: "1.4"},
        {id: "1.5", name: "thrash metal", parent: "1"},
            {id: "1.5.1", name: "Old School Thrash", parent: "1.5"},
            {id: "1.5.2", name: "Progressive Thrash", parent: "1.5"},

    {id: "2", name: "rock", parent: null},
        {id: "2.1", name: "hard rock", parent: "2" },
        {id: "2.2", name: "progressive rock", parent: "2" },
            {id: "2.2.1", name: "eclectic prog", parent: "2.2" },
            {id: "2.2.2", name: "jazz-fusion prog", parent: "2.2" },
            {id: "2.2.3", name: "neo-prog", parent: "2.2" },
            {id: "2.2.4", name: "symphonic prog", parent: "2.2" },
        {id: "2.3", name: "psychedelic rock", parent: "2" },
];